stages = ['''
  +---+
  |   |
  O   |
 /|\  |
 / \  |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
 /    |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|\  |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
 /|   |
      |
      |
=========''', '''
  +---+
  |   |
  O   |
  |   |
      |
      |
=========
''', '''
  +---+
  |   |
  O   |
      |
      |
      |
=========
''', '''
  +---+
  |   |
      |
      |
      |
      |
=========
''']
chosen_word=""
s=input("enter y to yourself choose the word \nElse press n so that computer may proceede with autogenerated word ")
if s=="y":
    chosen_word=input("enter the word ")
else:
    chosen_word="cigarette"    

l1=[]
l2=[]
l=len(chosen_word)
for i in range (0,l) :
    l1.append("_")
    l2.append(chosen_word[i])

c=7   
while (l1 != l2 and c>0):
    guess=input("enter the guess letter : ")
   
    n=0
    for i in range(0,l):
        
        if l2[i]==guess:
            l1[i]=guess
            n=n+1
                 
    if n==0:
        c=c-1
        print("wrong guess\n")

    print(l1)
    print(stages[c])

if(l1==l2):
    print ("congo... you won !!!!")
if(c==0):
    print("sorry... you were unable to guess withing the given no. of chances")
